"""OpenFOAM case skeleton export for downstream industrial CFD."""

from __future__ import annotations

from io import BytesIO
from zipfile import ZIP_DEFLATED, ZipFile

from .simple_solver import CFDInput


def generate_openfoam_case_files(config: CFDInput) -> dict[str, str]:
    """Generate an OpenFOAM case skeleton as path-to-text mapping."""
    nu = config.viscosity_Pa_s / max(config.density_kg_m3, 1.0)
    alpha = config.thermal_conductivity_W_mK / max(config.density_kg_m3 * config.Cp_kJ_kgK * 1000.0, 1.0)
    solver = "simpleFoam"
    files = {
        "README_OpenFOAM.md": _readme_text(solver),
        "system/controlDict": _control_dict(solver),
        "system/controlDict.scalarTransportFoam": _control_dict("scalarTransportFoam"),
        "system/fvSchemes": _fv_schemes(),
        "system/fvSolution": _fv_solution(),
        "system/blockMeshDict": _block_mesh_dict(config),
        "constant/transportProperties": f"""FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      transportProperties;
}}
transportModel  Newtonian;
nu              [0 2 -1 0 0 0 0] {nu:.8e};
rho             [1 -3 0 0 0 0 0] {config.density_kg_m3:.6g};
alpha           [0 2 -1 0 0 0 0] {alpha:.8e};
""",
        "constant/thermophysicalProperties": f"""FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      thermophysicalProperties;
}}
// Skeleton only: replace with full polymer-solution thermophysical model for production CFD.
rho     {config.density_kg_m3:.6g};
Cp      {config.Cp_kJ_kgK * 1000.0:.6g};
kappa   {config.thermal_conductivity_W_mK:.6g};
""",
        "0/U": _field_U(config),
        "0/p": _field_p(config),
        "0/T": _field_T(config),
        "0/C_ENB": _field_scalar("C_ENB", config.inlet_C_ENB_mol_m3),
        "0/C": _field_scalar("C", config.inlet_C_ENB_mol_m3),
    }
    return files


def export_openfoam_case_zip(config: CFDInput) -> bytes:
    """Return a zipped OpenFOAM case skeleton."""
    buffer = BytesIO()
    with ZipFile(buffer, "w", ZIP_DEFLATED) as archive:
        for path, text in generate_openfoam_case_files(config).items():
            archive.writestr(path, text)
    return buffer.getvalue()


def _readme_text(solver: str) -> str:
    return f"""# EPDM OpenFOAM case skeleton

This case is generated by the metallocene EPDM process simulator.

It is a starting skeleton, not a validated industrial CFD model. Replace the
mesh, boundary patches, rheology, turbulence model and thermophysical model
with plant-specific data before design use.

Typical workflow:

```bash
blockMesh
{solver}
paraFoam
```

For scalar heat/species transport, copy `system/controlDict.scalarTransportFoam`
to `system/controlDict` and run:

```bash
scalarTransportFoam
paraFoam
```

Boundary patch names are kept consistent across `system/blockMeshDict`, `0/U`,
`0/p`, `0/T`, `0/C` and `0/C_ENB`: inlet, outlet, walls, frontAndBack.
"""


def _control_dict(solver: str) -> str:
    return f"""FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      controlDict;
}}
application     {solver};
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         500;
deltaT          1;
writeControl    timeStep;
writeInterval   100;
purgeWrite      0;
writeFormat     ascii;
writePrecision  6;
timeFormat      general;
timePrecision   6;
runTimeModifiable true;
"""


def _fv_schemes() -> str:
    return """FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      fvSchemes;
}
ddtSchemes { default steadyState; }
gradSchemes { default Gauss linear; }
divSchemes
{
    default none;
    div(phi,U) Gauss upwind;
}
laplacianSchemes { default Gauss linear corrected; }
interpolationSchemes { default linear; }
snGradSchemes { default corrected; }
"""


def _fv_solution() -> str:
    return """FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      fvSolution;
}
solvers
{
    p { solver PCG; preconditioner DIC; tolerance 1e-06; relTol 0.05; }
    U { solver smoothSolver; smoother symGaussSeidel; tolerance 1e-05; relTol 0.1; }
}
SIMPLE
{
    nNonOrthogonalCorrectors 0;
}
relaxationFactors
{
    fields { p 0.3; }
    equations { U 0.7; }
}
"""


def _block_mesh_dict(config: CFDInput) -> str:
    L = config.geometry.pipe_length_m if config.geometry.geometry_type == "Pipe 2D" else config.geometry.reactor_diameter_m
    D = config.geometry.pipe_diameter_m if config.geometry.geometry_type == "Pipe 2D" else config.geometry.reactor_diameter_m
    return f"""FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      blockMeshDict;
}}
convertToMeters 1;
vertices
(
    (0 0 0) ({L:.6g} 0 0) ({L:.6g} {D:.6g} 0) (0 {D:.6g} 0)
    (0 0 0.01) ({L:.6g} 0 0.01) ({L:.6g} {D:.6g} 0.01) (0 {D:.6g} 0.01)
);
blocks
(
    hex (0 1 2 3 4 5 6 7) ({config.geometry.nx} {config.geometry.ny} 1) simpleGrading (1 1 1)
);
edges ();
boundary
(
    inlet {{ type patch; faces ((0 4 7 3)); }}
    outlet {{ type patch; faces ((1 2 6 5)); }}
    walls {{ type wall; faces ((0 1 5 4) (3 7 6 2)); }}
    frontAndBack {{ type empty; faces ((0 3 2 1) (4 5 6 7)); }}
);
mergePatchPairs ();
"""


def _field_U(config: CFDInput) -> str:
    return f"""FoamFile
{{
    version 2.0;
    format ascii;
    class volVectorField;
    object U;
}}
dimensions [0 1 -1 0 0 0 0];
internalField uniform ({config.inlet_velocity_m_s:.6g} 0 0);
boundaryField
{{
    inlet {{ type fixedValue; value uniform ({config.inlet_velocity_m_s:.6g} 0 0); }}
    outlet {{ type zeroGradient; }}
    walls {{ type noSlip; }}
    frontAndBack {{ type empty; }}
}}
"""


def _field_p(config: CFDInput) -> str:
    return f"""FoamFile
{{
    version 2.0;
    format ascii;
    class volScalarField;
    object p;
}}
dimensions [0 2 -2 0 0 0 0];
internalField uniform {config.outlet_pressure_Pa:.6g};
boundaryField
{{
    inlet {{ type zeroGradient; }}
    outlet {{ type fixedValue; value uniform {config.outlet_pressure_Pa:.6g}; }}
    walls {{ type zeroGradient; }}
    frontAndBack {{ type empty; }}
}}
"""


def _field_T(config: CFDInput) -> str:
    return _field_scalar("T", config.inlet_temperature_C + 273.15)


def _field_scalar(name: str, value: float) -> str:
    return f"""FoamFile
{{
    version 2.0;
    format ascii;
    class volScalarField;
    object {name};
}}
dimensions [0 0 0 0 0 0 0];
internalField uniform {value:.6g};
boundaryField
{{
    inlet {{ type fixedValue; value uniform {value:.6g}; }}
    outlet {{ type zeroGradient; }}
    walls {{ type zeroGradient; }}
    frontAndBack {{ type empty; }}
}}
"""
