"""Metallocene EPM/EPDM solution polymerization process simulator and digital twin."""

__all__ = [
    "components",
    "state",
    "streams",
    "thermo",
    "kinetics",
    "reactor",
    "dynamic_reactor",
    "dynamic_template_reactor",
    "template_ode_rhs",
    "template_config",
    "template_flowsheet",
    "state_vector",
    "flash",
    "polymer_props",
    "flowsheet",
    "sensitivity",
    "optimizer",
    "report",
    "plotting",
    "equipment_3d",
    "layout_3d",
    "digital_twin_3d",
    "utils",
    "unitops",
    "heat_balance",
    "fluid_props",
    "calibration",
    "experiment_data",
    "parameter_estimation",
    "recipe",
    "db",
    "uncertainty",
    "equation_registry",
    "dimensional_checks",
    "time_series_data",
    "profile_alignment",
    "bayesian_doe",
    "property_confidence",
    "surrogate",
    "repro_package",
    "posterior",
    "constrained_window",
    "audit_trail",
    "workflow_wizard",
    "case_manager",
    "recycle_solver",
    "safety",
    "scaleup",
    "cfd",
]

__version__ = "0.7.4"
APP_VERSION = "V6.4 / 0.7.4"
